services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    user: mysql
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3306
    restart: always
    env_file:
      - path: .env
    volumes:
      - mariadb:/var/lib/mysql

  adminer:
    container_name: adminer
    hostname: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 8080
    restart: always
    depends_on:
      - mariadb

  redis:
    container_name: redis
    hostname: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 6379
    restart: always

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 9000
    restart: always
    env_file:
      - path: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    env_file:
      - path: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  ftp:
    container_name: ftp
    hostname: ftp
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "40000-40004:40000-40004"
    networks:
      - inception
    restart: always
    env_file:
      - path: .env
    volumes:
      - wordpress:/home/ftpuser/ftp
    depends_on:
      - nginx

  site-statique:
    container_name: site-statique
    hostname: site-statique
    build:
      context: ./requirements/bonus/site-statique
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - inception
    restart: always

  grafana:
    container_name: grafana
    hostname: grafana
    build:
      context: ./requirements/bonus/grafana
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3443:443"
    networks:
      - inception
    restart: always
    env_file:
      - path: .env
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - nginx

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/database'
  grafana:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gui/data/grafana'

networks:
  inception:
    driver: bridge